name: Deploy/Destroy EC2 Dashboard

on:
  workflow_dispatch:
    inputs:
      ACTION:
        description: "Choose 'deploy' to apply or 'destroy' to tear down"
        required: true
        default: "deploy"
        type: choice
        options: [deploy, destroy]
      ENVIRONMENT:
        description: "GitHub Environment name (must exist)"
        required: true
        default: "mypersonalAWS"
      AWS_REGION:
        description: "AWS Region"
        required: true
        default: "us-east-2"
      WEBSITE_BUCKET_NAME:
        description: "(Optional) S3 bucket name for site (blank to auto-generate)"
        required: false
        default: ""
      ALLOWED_EMAIL_DOMAIN:
        description: "Allowed email domain for OTP/login (deploy only)"
        required: false
        default: "gmail.com"
      SES_SENDER_EMAIL:
        description: "SES verified sender address (deploy only)"
        required: false
        default: "noreplyzingamazigle@gmail.com"
      TF_BACKEND_BUCKET:
        description: "(Optional) Pre-existing S3 bucket for TF state. Leave blank to auto-create."
        required: false
        default: ""
      TF_LOCK_TABLE:
        description: "(Optional) Pre-existing DynamoDB lock table. Leave blank to auto-create."
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (from environment secrets)
        run: |
          echo "Configuring AWS credentials from environment secrets"
          mkdir -p ~/.aws
          cat > ~/.aws/credentials <<EOF
          [default]
          aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          cat > ~/.aws/config <<EOF
          [default]
          region=${{ inputs.AWS_REGION }}
          output=json
          EOF

      # ---------- BOOTSTRAP BACKEND: create S3 state bucket + DynamoDB lock table if missing ----------
      - name: Bootstrap Terraform backend (S3 + DynamoDB)
        id: backend
        shell: bash
        run: |
          set -euo pipefail

          REGION="${{ inputs.AWS_REGION }}"
          ENVNAME="${{ inputs.ENVIRONMENT }}"
          USER_BUCKET="${{ inputs.TF_BACKEND_BUCKET }}"
          USER_TABLE="${{ inputs.TF_LOCK_TABLE }}"

          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          # Compose safe, globally unique defaults if not provided
          # Bucket names must be lowercase and globally unique
          if [ -z "$USER_BUCKET" ]; then
            RAW="tfstate-${ENVNAME}-${ACCOUNT_ID}-${REGION}"
            BUCKET=$(echo "$RAW" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9.-' '-')
          else
            BUCKET="$USER_BUCKET"
          fi

          if [ -z "$USER_TABLE" ]; then
            TABLE="tf-lock-${ENVNAME}"
          else
            TABLE="$USER_TABLE"
          fi

          echo "Using backend bucket: $BUCKET"
          echo "Using lock table   : $TABLE"

          # Create S3 bucket if it doesn't exist
          if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
            echo "Bucket exists: $BUCKET"
          else
            echo "Creating bucket: $BUCKET (region: $REGION)"
            if [ "$REGION" = "us-east-1" ]; then
              aws s3api create-bucket --bucket "$BUCKET"
            else
              aws s3api create-bucket --bucket "$BUCKET" --create-bucket-configuration LocationConstraint="$REGION"
            fi
          fi

          # Recommended settings: versioning, encryption, public access block
          aws s3api put-bucket-versioning --bucket "$BUCKET" --versioning-configuration Status=Enabled
          aws s3api put-bucket-encryption --bucket "$BUCKET" --server-side-encryption-configuration '{
            "Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]
          }'
          aws s3api put-public-access-block --bucket "$BUCKET" --public-access-block-configuration '{
            "BlockPublicAcls":true,"IgnorePublicAcls":true,"BlockPublicPolicy":true,"RestrictPublicBuckets":true
          }'

          # Create DynamoDB table if it doesn't exist
          if aws dynamodb describe-table --table-name "$TABLE" >/dev/null 2>&1; then
            echo "DynamoDB table exists: $TABLE"
          else
            echo "Creating DynamoDB table: $TABLE"
            aws dynamodb create-table \
              --table-name "$TABLE" \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST \
              --region "$REGION"
            aws dynamodb wait table-exists --table-name "$TABLE" --region "$REGION"
          fi

          echo "bucket=$BUCKET" >> "$GITHUB_OUTPUT"
          echo "table=$TABLE"   >> "$GITHUB_OUTPUT"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ steps.backend.outputs.bucket }}" \
            -backend-config="key=env/${{ inputs.ENVIRONMENT }}/terraform.tfstate" \
            -backend-config="region=${{ inputs.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ steps.backend.outputs.table }}"

      # -------------------- DEPLOY PATH --------------------
      - name: Terraform Apply (deploy)
        if: ${{ inputs.ACTION == 'deploy' }}
        env:
          TF_VAR_aws_region: ${{ inputs.AWS_REGION }}
          TF_VAR_allowed_email_domain: ${{ inputs.ALLOWED_EMAIL_DOMAIN }}
          TF_VAR_ses_sender_email: ${{ inputs.SES_SENDER_EMAIL }}
          TF_VAR_website_bucket_name: ${{ inputs.WEBSITE_BUCKET_NAME }}
        run: terraform apply -auto-approve

      - name: Capture outputs (deploy)
        if: ${{ inputs.ACTION == 'deploy' }}
        id: out
        run: |
          set +e
          terraform output -raw api_endpoint      > .api.txt   2>/dev/null || true
          terraform output -raw cloudfront_domain > .cf.txt    2>/dev/null || true
          terraform output -raw site_bucket       > .site.txt  2>/dev/null || true
          terraform output -raw cloudfront_id     > .cfid.txt  2>/dev/null || true
          set -e
          echo "api=$(cat .api.txt  || true)"   >> $GITHUB_OUTPUT
          echo "cf=$(cat .cf.txt   || true)"    >> $GITHUB_OUTPUT
          echo "site=$(cat .site.txt|| true)"   >> $GITHUB_OUTPUT
          echo "cfid=$(cat .cfid.txt|| true)"   >> $GITHUB_OUTPUT

      - name: Build site (template API + domain) (deploy)
        if: ${{ inputs.ACTION == 'deploy' }}
        run: |
          mkdir -p dist
          cp -r html/* dist/
          sed -i "s|\${api_base_url}|${{ steps.out.outputs.api }}|g" dist/index.html.tpl
          sed -i "s|\${api_base_url}|${{ steps.out.outputs.api }}|g" dist/login.html
          sed -i "s|\${allowed_email_domain}|${{ inputs.ALLOWED_EMAIL_DOMAIN }}|g" dist/index.html.tpl
          mv dist/index.html.tpl dist/index.html

      - name: Upload to S3 (deploy)
        if: ${{ inputs.ACTION == 'deploy' }}
        run: aws s3 sync dist s3://${{ steps.out.outputs.site }} --delete --acl private

      - name: Invalidate CloudFront cache (deploy)
        if: ${{ inputs.ACTION == 'deploy' && steps.out.outputs.cfid != '' }}
        run: aws cloudfront create-invalidation --distribution-id "${{ steps.out.outputs.cfid }}" --paths "/*"

      - name: Summary (deploy)
        if: ${{ inputs.ACTION == 'deploy' }}
        run: |
          echo "CloudFront URL: https://${{ steps.out.outputs.cf }}"
          echo "API Base URL:  ${{ steps.out.outputs.api }}"
          echo "Site Bucket:   ${{ steps.out.outputs.site }}"
          echo "TF State Bucket: ${{ steps.backend.outputs.bucket }}"
          echo "TF Lock Table:   ${{ steps.backend.outputs.table }}"

      # -------------------- DESTROY PATH --------------------
      - name: Try to capture outputs (destroy)
        if: ${{ inputs.ACTION == 'destroy' }}
        id: destroy_out
        continue-on-error: true
        run: |
          set +e
          terraform output -raw site_bucket   > .site.txt 2>/dev/null || true
          terraform output -raw cloudfront_id > .cfid.txt 2>/dev/null || true
          terraform output -raw api_endpoint  > .api.txt  2>/dev/null || true
          terraform output -raw cloudfront_domain > .cf.txt 2>/dev/null || true
          set -e
          echo "site=$(cat .site.txt  || true)"  >> $GITHUB_OUTPUT
          echo "cfid=$(cat .cfid.txt  || true)"  >> $GITHUB_OUTPUT
          echo "api=$(cat .api.txt    || true)"  >> $GITHUB_OUTPUT
          echo "cf=$(cat .cf.txt      || true)"  >> $GITHUB_OUTPUT

      - name: Empty website bucket (destroy – safe/optional)
        if: ${{ inputs.ACTION == 'destroy' && steps.destroy_out.outputs.site != '' }}
        continue-on-error: true
        run: |
          echo "Emptying bucket s3://${{ steps.destroy_out.outputs.site }} if it exists..."
          aws s3 rm s3://${{ steps.destroy_out.outputs.site }} --recursive || true

      - name: Terraform Destroy
        if: ${{ inputs.ACTION == 'destroy' }}
        env:
          TF_VAR_aws_region: ${{ inputs.AWS_REGION }}
          TF_VAR_allowed_email_domain: ${{ inputs.ALLOWED_EMAIL_DOMAIN }}
          TF_VAR_ses_sender_email: ${{ inputs.SES_SENDER_EMAIL }}
          TF_VAR_website_bucket_name: ${{ inputs.WEBSITE_BUCKET_NAME }}
        run: terraform destroy -auto-approve

      - name: Summary (destroy)
        if: ${{ inputs.ACTION == 'destroy' }}
        run: |
          echo "Destroy completed (or attempted)."
          echo "Backend kept:"
          echo "  TF State Bucket: ${{ steps.backend.outputs.bucket }}"
          echo "  TF Lock Table:   ${{ steps.backend.outputs.table }}"
